export interface WordEntry {
  text: string;
  difficulty: number;
  points: number;
  speed: number;
}

export const WORDS: WordEntry[] = [
  // Easy (3-4 letters) — Wave 1-2
  { text: 'the', difficulty: 1, points: 10, speed: 30 },
  { text: 'and', difficulty: 1, points: 10, speed: 30 },
  { text: 'for', difficulty: 1, points: 10, speed: 30 },
  { text: 'not', difficulty: 1, points: 10, speed: 30 },
  { text: 'you', difficulty: 1, points: 10, speed: 30 },
  { text: 'all', difficulty: 1, points: 10, speed: 30 },
  { text: 'can', difficulty: 1, points: 10, speed: 30 },
  { text: 'had', difficulty: 1, points: 10, speed: 30 },
  { text: 'her', difficulty: 1, points: 10, speed: 30 },
  { text: 'was', difficulty: 1, points: 10, speed: 30 },
  { text: 'one', difficulty: 1, points: 10, speed: 30 },
  { text: 'our', difficulty: 1, points: 10, speed: 30 },
  { text: 'out', difficulty: 1, points: 10, speed: 30 },
  { text: 'day', difficulty: 1, points: 10, speed: 30 },
  { text: 'get', difficulty: 1, points: 10, speed: 30 },
  { text: 'has', difficulty: 1, points: 10, speed: 30 },
  { text: 'how', difficulty: 1, points: 10, speed: 30 },
  { text: 'new', difficulty: 1, points: 10, speed: 30 },
  { text: 'see', difficulty: 1, points: 10, speed: 30 },
  { text: 'way', difficulty: 1, points: 10, speed: 30 },
  { text: 'run', difficulty: 1, points: 10, speed: 30 },
  { text: 'top', difficulty: 1, points: 10, speed: 30 },
  { text: 'red', difficulty: 1, points: 10, speed: 30 },
  { text: 'sun', difficulty: 1, points: 10, speed: 30 },
  { text: 'sea', difficulty: 1, points: 10, speed: 30 },
  { text: 'sky', difficulty: 1, points: 10, speed: 30 },
  { text: 'big', difficulty: 1, points: 10, speed: 30 },
  { text: 'dog', difficulty: 1, points: 10, speed: 30 },
  { text: 'eat', difficulty: 1, points: 10, speed: 30 },

  // Medium (5-6 letters) — Wave 3-4
  { text: 'about', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'after', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'again', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'below', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'could', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'every', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'first', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'found', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'great', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'house', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'large', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'learn', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'never', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'other', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'place', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'point', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'right', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'small', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'sound', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'still', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'study', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'their', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'there', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'thing', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'think', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'three', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'water', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'where', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'which', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'world', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'would', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'write', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'rapid', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'focus', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'craft', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'shift', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'power', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'force', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'storm', difficulty: 1.5, points: 25, speed: 35 },
  { text: 'flame', difficulty: 1.5, points: 25, speed: 35 },

  // Hard (7-8 letters) — Wave 5-7
  { text: 'ability', difficulty: 2, points: 40, speed: 38 },
  { text: 'balance', difficulty: 2, points: 40, speed: 38 },
  { text: 'capture', difficulty: 2, points: 40, speed: 38 },
  { text: 'dynamic', difficulty: 2, points: 40, speed: 38 },
  { text: 'element', difficulty: 2, points: 40, speed: 38 },
  { text: 'fashion', difficulty: 2, points: 40, speed: 38 },
  { text: 'general', difficulty: 2, points: 40, speed: 38 },
  { text: 'habitat', difficulty: 2, points: 40, speed: 38 },
  { text: 'imagine', difficulty: 2, points: 40, speed: 38 },
  { text: 'journey', difficulty: 2, points: 40, speed: 38 },
  { text: 'kitchen', difficulty: 2, points: 40, speed: 38 },
  { text: 'library', difficulty: 2, points: 40, speed: 38 },
  { text: 'machine', difficulty: 2, points: 40, speed: 38 },
  { text: 'natural', difficulty: 2, points: 40, speed: 38 },
  { text: 'obscure', difficulty: 2, points: 40, speed: 38 },
  { text: 'perfect', difficulty: 2, points: 40, speed: 38 },
  { text: 'quality', difficulty: 2, points: 40, speed: 38 },
  { text: 'reality', difficulty: 2, points: 40, speed: 38 },
  { text: 'science', difficulty: 2, points: 40, speed: 38 },
  { text: 'triumph', difficulty: 2, points: 40, speed: 38 },
  { text: 'uniform', difficulty: 2, points: 40, speed: 38 },
  { text: 'venture', difficulty: 2, points: 40, speed: 38 },
  { text: 'weather', difficulty: 2, points: 40, speed: 38 },
  { text: 'extreme', difficulty: 2, points: 40, speed: 38 },
  { text: 'measure', difficulty: 2, points: 40, speed: 38 },
  { text: 'network', difficulty: 2, points: 40, speed: 38 },
  { text: 'organic', difficulty: 2, points: 40, speed: 38 },
  { text: 'pattern', difficulty: 2, points: 40, speed: 38 },
  { text: 'quantum', difficulty: 2, points: 40, speed: 38 },
  { text: 'reflect', difficulty: 2, points: 40, speed: 38 },
  { text: 'destroy', difficulty: 2, points: 40, speed: 38 },
  { text: 'phantom', difficulty: 2, points: 40, speed: 38 },
  { text: 'crystal', difficulty: 2, points: 40, speed: 38 },
  { text: 'voltage', difficulty: 2, points: 40, speed: 38 },

  // Expert (9+ letters) — Wave 8+
  { text: 'absolute', difficulty: 3, points: 70, speed: 40 },
  { text: 'beautiful', difficulty: 3, points: 80, speed: 42 },
  { text: 'challenge', difficulty: 3, points: 80, speed: 42 },
  { text: 'dangerous', difficulty: 3, points: 80, speed: 42 },
  { text: 'elaborate', difficulty: 3, points: 80, speed: 42 },
  { text: 'fantastic', difficulty: 3, points: 80, speed: 42 },
  { text: 'gorgeous', difficulty: 3, points: 80, speed: 42 },
  { text: 'hurricane', difficulty: 3, points: 80, speed: 42 },
  { text: 'immediate', difficulty: 3, points: 80, speed: 42 },
  { text: 'knowledge', difficulty: 3, points: 80, speed: 42 },
  { text: 'landscape', difficulty: 3, points: 80, speed: 42 },
  { text: 'marvelous', difficulty: 3, points: 80, speed: 42 },
  { text: 'narrative', difficulty: 3, points: 80, speed: 42 },
  { text: 'offensive', difficulty: 3, points: 80, speed: 42 },
  { text: 'panoramic', difficulty: 3, points: 80, speed: 42 },
  { text: 'questions', difficulty: 3, points: 80, speed: 42 },
  { text: 'recording', difficulty: 3, points: 80, speed: 42 },
  { text: 'structure', difficulty: 3, points: 80, speed: 42 },
  { text: 'technique', difficulty: 3, points: 80, speed: 42 },
  { text: 'ultimate', difficulty: 3, points: 80, speed: 42 },
  { text: 'vibration', difficulty: 3, points: 80, speed: 42 },
  { text: 'awakening', difficulty: 3, points: 80, speed: 42 },
  { text: 'brilliance', difficulty: 3, points: 90, speed: 44 },
  { text: 'conspiracy', difficulty: 3, points: 90, speed: 44 },
  { text: 'discovery', difficulty: 3, points: 90, speed: 44 },
  { text: 'evolution', difficulty: 3, points: 90, speed: 44 },
  { text: 'invisible', difficulty: 3, points: 80, speed: 42 },
  { text: 'legendary', difficulty: 3, points: 90, speed: 44 },
  { text: 'mythical', difficulty: 3, points: 80, speed: 42 },
  { text: 'supernova', difficulty: 3, points: 90, speed: 44 },
  { text: 'twilight', difficulty: 3, points: 80, speed: 42 },
  { text: 'threshold', difficulty: 3, points: 90, speed: 44 },
];

export function getWordsForWave(wave: number): WordEntry[] {
  if (wave <= 2) return WORDS.filter(w => w.difficulty <= 1);
  if (wave <= 4) return WORDS.filter(w => w.difficulty <= 1.5);
  if (wave <= 7) return WORDS.filter(w => w.difficulty <= 2);
  return WORDS;
}

export function getSpawnInterval(wave: number): number {
  return Math.max(800, 2500 - wave * 150);
}

export function getSpeedMultiplier(wave: number): number {
  return 1 + (wave - 1) * 0.08;
}
